name: push-translations

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Update the files
    - name: Update the files
      run: |
        jb config sphinx .
        sphinx-build -b gettext . _build/gettext
        sphinx-intl update -p _build/gettext 
        rm conf.py  

    # Make a PR, because right now I don't feel like setting up the conditional push patterns to make this not recursive
    - name: Make a PR
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b translation_file_update
          git add .
          git commit -m "auto generated translation file updates"
          git push -u origin translation_file_update

    
